import { reactive } from "vue"

export default reactive([
    {
        id: 0,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 1,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 2,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 3,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 4,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 5,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 6,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 7,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 8,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 9,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 10,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 11,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 12,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 13,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 14,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 15,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 16,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 17,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 18,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 19,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 20,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 21,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: {
            id: 0,
            name: "PRO",
        },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 0,
        show: true,
    },
    {
        id: 22,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: null,
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 1,
        show: true,
    },
    {
        id: 23,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 24,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 25,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 26,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 27,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 28,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
    {
        id: 29,
        first_name: "Кирилл",
        last_name: "Зуб",
        patronymic: "Николаевич",
        email: "kirillzzub@yandex.ru",
        tarif: { id: 1, name: "BASE" },
        avatar: `https://cdn.vuetifyjs.com/images/cards/sunshine.jpg`,
        created: 1690270352,
        status_id: 2,
        show: false,
    },
])